from PIL import Image, ImageFilter
im = Image.open("bilde.jpg")
print(im.format, im.size, im.mode)
im.show()
izmers = (200, 200)
im.thumbnail(izmers)
im.save("bilde-maza.jpg", im.format)
im.show()
im = im.rotate(180)
r, g, b = im.split()
im = Image.merge("RGB", (g,r,b))
im = im.filter(ImageFilter.BLUR)
im = im.filter(ImageFilter.DETAIL)
im.show()
im = im.filter(ImageFilter.BLUR)
im.show()
